### ISSUE TITLE
Overlap view doesn't properly handle non-standard cosine images

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Register#9]
Example file:

```
mincheader ADNI_002_S_4171_MR_MT1__N3m_Br_20110816094410627_S118013_I250649.mnc | grep cosine
        xspace:direction_cosines = 0.994712372831012, -0.0633894056081772, -0.0808025076985359 ;
        yspace:direction_cosines = 0.0725537820139018, 0.990589737892151, 0.116051509976387 ;
        zspace:direction_cosines = -0.0726857007469455, 0.121300406754017, 0.989951014518738 ;
```

Image:
![screenshot from 2016-03-01 10 32 18](https://cloud.githubusercontent.com/assets/3001850/13431806/f019814c-df98-11e5-84a9-f76f05c8c63f.png)

Note that the view non-overlapping looks fine.

**Comment by rdvincent** [comment]
@gdevenyi Is this built from the current develop branch?

I'm out of town and don't have access to ADNI data. Is there any chance you could send me a link to the offending file? I don't see similar deformation with the files that I do have.

**Comment by gdevenyi** [comment]
This is up to date with develop.

See email for the example file.

**Comment by rdvincent** [comment]
I think the issue with this file is that it (surprisingly) defines a "shear" component. Normally our direction cosines only define a rigid transformation. But here the transform specifies a shear, so that gets displayed when you superimpose the images. I'm not sure how to handle this - we could refuse to recognize the shear, or we could try to figure out if it's incorrect for the image to have these direction cosines to begin with. Finally, I suppose we could check the transform and issue a warning of we detect a non-rigid transform.

My guess is that there was something wrong with either the original acquisition, or the conversion to MINC. Either way, I'd argue that Display and register are doing the right thing - they are respecting the weird direction cosines and displaying the sheared image. Another clue is that the shear disappears if the signs of the X and Y components of the Z direction cosines are flipped, e.g. if I change zspace:direction_cosines from

`-0.0727    0.1213    0.9900`

to 

`0.0727    -0.1213    0.9900`

**Comment by gdevenyi** [comment]
Okay, well, it's a broken file, but it's the original from ADNI, not much to be done there.

I think a warning is probably the most appropriate.

**Comment by rdvincent** [comment]
I agree. I would imagine that some modalities (e.g. ultrasound) might naturally incorporate a shear component. It's nothing I would expect in an MRI, though.

**Comment by gdevenyi** [comment]
Fixed.
